
/**
 * This file was generated by EverDev.
 * EverDev is a part of EVER OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

// This is class that describes you smart contract.
contract test {
fallback (uint a) external {
    
}
}
